client/store/index.js

fix: removed user from store index

fix: removed user from store index

---

package-lock.json
package.json
public/index.html

feat:added material ui

---

client/components/signup.js
package-lock.json
public/style.css

The form format closely follows the following example provided by Material UI:
GitHub:
https://github.com/mui-org/material-ui/blob/master/docs/src/pages/getting-started/page-layout-examples/sign-up/SignUp.js
Webpage:
https://material-ui.com/getting-started/page-layout-examples/sign-up/
To apply styling for class components, higher order component API was required:
https://material-ui.com/styles/basics/#higher-order-component-api
https://stackoverflow.com/questions/56432167/how-to-style-class-components-using-makestyles-in-material-ui

feat: added css styling for sign-up page

---

client/components/login.js
client/components/signup.js
client/components/user-home.js
functions/.gitignore
functions/index.js
functions/package-lock.json
functions/package.json
package-lock.json
public/style.css

feat:styled login page

---

client/components/room.js
client/store/roomId.js
client/store/user.js
client/workers/TargetSumWorker.js

---
Feat: Added switch statement and webworkers. Tests now work.

Webworkers

---

.travis.yml
client/components/user-home.spec.js
script/seed.spec.js

continuous integration

---

client/components/ProblemsSolved.js
client/components/UserProfile.js
client/components/room.js
client/store/user.js
package-lock.json

User profile

---

client/components/AvailableRooms.js
client/components/user-home.js
client/store/roomId.js

fix: Updated room-list logic. Visible if users < 2

---

client/components/ProblemsSolved.js
client/components/UserProfile.js
client/components/user-home.js
client/store/roomId.js

Points earned

---

client/components/AvailableRooms.js
client/components/user-home.js
client/components/user-home.spec.js
functions/index.js
package-lock.json
package.json

User home tests

---

client/components/signup.js
client/components/signup.spec.js

Test: created test for sign up component

---

client/components/login.js
client/components/login.spec.js

test: created tests for Login component

---

client/components/room.js
client/workers/ReverseWordsWorker.js

Feat: added reverse words problem to list of problems

---

client/components/AvailableRooms.js
client/components/CountDown.js
client/components/JoinSpecificRoom.js
client/components/UserProfile.js
client/components/room.js
client/components/user-home.js
client/workers/ReturnNegative.js

feat: added return negative problem and added error handling for join room

feat: added return negative problem and added error handling for join room

---

client/components/room.js
client/workers/Intersection.js

feat: added Intesection to list of algo problems

---

client/components/EmptyState.js
client/components/user-home.js
client/components/user-home.spec.js
client/store/auth.js
package-lock.json

fix: fixed userhome spec

---

client/components/room.js
client/workers/PalindromeWorker.js

Fix:palindrome tests now work

---

client/components/CountDown.js
client/components/room.js
client/workers/PalindromeWorker.js

---
Feat: color red for 10 seconds or less until switch

Color countdown

---

client/components/ProblemsSolved.js
client/components/UserProfile.js
client/store/auth.js
client/store/roomId.js

Results are now updating the 'solved' field, reflected on user profile (only solved problems give you points). Two people joining a room will not mark it as solved.

Room results user points

---

client/components/room.js
client/workers/Intersection.js
client/workers/PalindromeWorker.js
client/workers/ReturnNegative.js
client/workers/ReverseWordsWorker.js
client/workers/TargetSumWorker.js
client/workers/TwoSumWorker.js

Feat: Tests now show pass or fail

---

client/components/UserProfile.js
client/components/user-home.js
client/store/roomId.js

Fix: points now reflected on profile and user-home

---

client/components/ProblemsSolved.js
client/components/room.js

feat: added pagination to table in user profile

---

client/components/AceCodeEditor.js

feat: starting code now displays new lines

---

client/components/room.js

fix: updated header room header message when user joins

---

client/components/EmptyState.js
client/components/Homepage.js

feat: included background image for homepage

---

client/components/AvailableRooms.js
client/components/Homepage.js
client/components/JoinSpecificRoom.js
client/components/RoomResults.js
client/components/room.js
client/components/user-home.js

User homepage

---

client/components/RoomResults.js
client/components/UserProfile.js
client/components/UserProfile.spec.js
client/components/room.js
client/components/user-home.js
client/components/user-home.spec.js

feat: styled roomresult with icons

feat: styled roomresult with icons

---

client/components/UserProfile.js
client/components/room.js
client/components/user-home.js

changed transparent header and buttons in room

---

client/components/user-home.js

fix: duplicate typo

---

client/components/Homepage.js

feat: updated homepage background image

---

client/components/AceCodeEditor.js

fix: fixed bug with curly braces on editor

---

README.md

doc: updated broken link for an image
